# Generated by Django 6.0.2 on 2026-03-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('meet_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Scheduling'), ('scheduled', 'Scheduled'), ('failed', 'Failed to Schedule'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.candidate')),
                ('diff_area_aom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diff_area_interviews', to=settings.AUTH_USER_MODEL)),
                ('same_area_aom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_area_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
